version: "3.9"

services: 
  django-backend:
    restart: always
    build:
      context: ./django-backend
    image: djangobackend
  postgresql-db:
    restart: always
    image: postgres
    env_file: ./postgresql-db/.pg-env
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
    - "80:80" # port exposed to outside world.
    - "443:443"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot # <--here
  certbot:
    image: certbot/certbot
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot # <--here
